spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/mylove?serverTimezone=GMT%2b8
   username: root
   password: 521011

  redis:
    host: 192.168.1.105
    port: 6397
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 100ms

server:
  port: 5210


